/*
 * RGBColors.h
 * Created by Jose Rivera, Feb 2018.
 *
 * This work is licensed under a Creative Commons Attribution 4.0 International License.
 * http://creativecommons.org/licenses/by/4.0/
 */

#include <inttypes.h>

#ifndef RGB_COLORS_H_
#define RGB_COLORS_H_

/**
 * Utils
 */
#define array_length(a) (sizeof(a) / sizeof(*a))

struct RGBColor
{
  uint8_t red;
  uint8_t green;
  uint8_t blue;
};

#define COLOR_RED 0xFF0000
#define COLOR_GREEN 0x00FF00
#define COLOR_BLUE 0x0000FF
#define COLOR_YELLOW 0xFFFF00
#define COLOR_CYAN 0x00FFFF
#define COLOR_WHITE 0xFFFFFF
#define COLOR_BLACK 0x000000
#define COLOR_AQUAMARINE 0x71DC94
#define COLOR_BLUEVIOLET 0x9F5F9F
#define COLOR_BROWN 0xA62B2B
#define COLOR_CADETBLUE 0x5F9F9F
#define COLOR_CORAL 0xFF7F00
#define COLOR_CORNFLOWERBLUE 0x43436F
#define COLOR_DARKGREEN 0x305030
#define COLOR_DARKOLIVEGREEN 0x505030
#define COLOR_DARKORCHID 0x9932CC
#define COLOR_DARKSLATEBLUE 0x6C248F
#define COLOR_DARKSLATEGRAY 0x305050
#define COLOR_DARKSLATEGREY 0x305050
#define COLOR_DARKTURQUOISE 0x7194DC
#define COLOR_FIREBRICK 0x8F2424
#define COLOR_FORESTGREEN 0x248F24
#define COLOR_GOLD 0xCC7F32
#define COLOR_GOLDENROD 0xDCDC71
#define COLOR_GREENYELLOW 0x94DC71
#define COLOR_INDIANRED 0x503030
#define COLOR_KHAKI 0x9F9F5F
#define COLOR_LIGHTBLUE 0xC0D9D9
#define COLOR_LIGHTSTEELBLUE 0x8F8FBD
#define COLOR_LIMEGREEN 0x32CC32
#define COLOR_MAROON 0x8F246C
#define COLOR_MEDIUMAQUAMARINE 0x32CC99
#define COLOR_MEDIUMBLUE 0x3232CC
#define COLOR_MEDIUMFORESTGREEN 0x6C8F24
#define COLOR_MEDIUMGOLDENROD 0xEAEAAD
#define COLOR_MEDIUMORCHID 0x9471DC
#define COLOR_MEDIUMSEAGREEN 0x436F43
#define COLOR_MEDIUMSLATEBLUE 0x7FFF00
#define COLOR_MEDIUMSPRINGGREEN 0x7FFF00
#define COLOR_MEDIUMTURQUOISE 0x71DCDC
#define COLOR_MEDIUMVIOLETRED 0xDC7194
#define COLOR_MIDNIGHTBLUE 0x303050
#define COLOR_NAVY 0x24248F
#define COLOR_NAVYBLUE 0x24248F
#define COLOR_ORANGE 0xFF8000
#define COLOR_ORANGERED 0xFF4000
#define COLOR_ORCHID 0xDC71DC
#define COLOR_PALEGREEN 0x8FBD8F
#define COLOR_PINK 0xBD8F8F
#define COLOR_PLUM 0xEAADEA
#define COLOR_SALMON 0x6F4343
#define COLOR_SEAGREEN 0x248F6C
#define COLOR_SIENNA 0x8F6C24
#define COLOR_SKYBLUE 0x3299CC
#define COLOR_SLATEBLUE 0x7FFF00
#define COLOR_SPRINGGREEN 0xFF7F00
#define COLOR_STEELBLUE 0x246C8F
#define COLOR_TAN 0xDC9471
#define COLOR_THISTLE 0xD9C0D9
#define COLOR_TURQUOISE 0xADEAEA
#define COLOR_VIOLET 0x503050
#define COLOR_VIOLETRED 0xCC3299
#define COLOR_WHEAT 0xD9D9C0
#define COLOR_YELLOWGREEN 0x99CC32
#define COLOR_SUMMERSKY 0x39B0DE
#define COLOR_RICHBLUE 0x5A5AAB
#define COLOR_BRASS 0xB6A643
#define COLOR_COPPER 0xB87333
#define COLOR_BRONZE 0x8D7824
#define COLOR_BRONZE2 0xA67D3E
#define COLOR_SILVER 0xE6E9FA
#define COLOR_BRIGHTGOLD 0xD9D91A
#define COLOR_OLDGOLD 0xCFB63B
#define COLOR_FELDSPAR 0xD29276
#define COLOR_QUARTZ 0xD9D9F3
#define COLOR_NEONPINK 0xFF6EC7
#define COLOR_DARKPURPLE 0x881F78
#define COLOR_NEONBLUE 0x4D4DFF
#define COLOR_COOLCOPPER 0xD9881A
#define COLOR_MANDARINORANGE 0xE37833
#define COLOR_LIGHTWOOD 0xE9C2A6
#define COLOR_MEDIUMWOOD 0xA68064
#define COLOR_DARKWOOD 0x855F43
#define COLOR_SPICYPINK 0xFF1DAE
#define COLOR_SEMISWEETCHOC 0x6C4327
#define COLOR_BAKERSCHOC 0x5C3317
#define COLOR_FLESH 0xF5CCB0
#define COLOR_NEWTAN 0xEBC79F
#define COLOR_NEWMIDNIGHTBLUE 0x00009C
#define COLOR_VERYDARKBROWN 0x5A2924
#define COLOR_DARKBROWN 0x5C4033
#define COLOR_DARKTAN 0x976950
#define COLOR_GREENCOPPER 0x527D76
#define COLOR_DKGREENCOPPER 0x4A766E
#define COLOR_DUSTYROSE 0x856464
#define COLOR_HUNTERSGREEN 0x225F50
#define COLOR_SCARLET 0x8D1717
#define COLOR_MED_PURPLE 0xBB29F5
#define COLOR_LIGHT_PURPLE 0xDE94FA
#define COLOR_VERY_LIGHT_PURPLE 0xF0CFFD

const uint32_t ALL_COLORS[] = {
  COLOR_WHITE,
  COLOR_RED,
  COLOR_GREEN,
  COLOR_BLUE,
  COLOR_YELLOW,
  COLOR_CYAN,
  COLOR_AQUAMARINE,
  COLOR_BLUEVIOLET,
  COLOR_BROWN,
  COLOR_CADETBLUE,
  COLOR_CORAL,
  COLOR_CORNFLOWERBLUE,
  COLOR_DARKGREEN,
  COLOR_DARKOLIVEGREEN,
  COLOR_DARKORCHID,
  COLOR_DARKSLATEBLUE,
  COLOR_DARKSLATEGRAY,
  COLOR_DARKSLATEGREY,
  COLOR_DARKTURQUOISE,
  COLOR_FIREBRICK,
  COLOR_FORESTGREEN,
  COLOR_GOLD,
  COLOR_GOLDENROD,
  COLOR_GREENYELLOW,
  COLOR_INDIANRED,
  COLOR_KHAKI,
  COLOR_LIGHTBLUE,
  COLOR_LIGHTSTEELBLUE,
  COLOR_LIMEGREEN,
  COLOR_MAROON,
  COLOR_MEDIUMAQUAMARINE,
  COLOR_MEDIUMBLUE,
  COLOR_MEDIUMFORESTGREEN,
  COLOR_MEDIUMGOLDENROD,
  COLOR_MEDIUMORCHID,
  COLOR_MEDIUMSEAGREEN,
  COLOR_MEDIUMSLATEBLUE,
  COLOR_MEDIUMSPRINGGREEN,
  COLOR_MEDIUMTURQUOISE,
  COLOR_MEDIUMVIOLETRED,
  COLOR_MIDNIGHTBLUE,
  COLOR_NAVY,
  COLOR_NAVYBLUE,
  COLOR_ORANGE,
  COLOR_ORANGERED,
  COLOR_ORCHID,
  COLOR_PALEGREEN,
  COLOR_PINK,
  COLOR_PLUM,
  COLOR_SALMON,
  COLOR_SEAGREEN,
  COLOR_SIENNA,
  COLOR_SKYBLUE,
  COLOR_SLATEBLUE,
  COLOR_SPRINGGREEN,
  COLOR_STEELBLUE,
  COLOR_TAN,
  COLOR_THISTLE,
  COLOR_TURQUOISE,
  COLOR_VIOLET,
  COLOR_VIOLETRED,
  COLOR_WHEAT,
  COLOR_YELLOWGREEN,
  COLOR_SUMMERSKY,
  COLOR_RICHBLUE,
  COLOR_BRASS,
  COLOR_COPPER,
  COLOR_BRONZE,
  COLOR_BRONZE2,
  COLOR_SILVER,
  COLOR_BRIGHTGOLD,
  COLOR_OLDGOLD,
  COLOR_FELDSPAR,
  COLOR_QUARTZ,
  COLOR_NEONPINK,
  COLOR_DARKPURPLE,
  COLOR_NEONBLUE,
  COLOR_COOLCOPPER,
  COLOR_MANDARINORANGE,
  COLOR_LIGHTWOOD,
  COLOR_MEDIUMWOOD,
  COLOR_DARKWOOD,
  COLOR_SPICYPINK,
  COLOR_SEMISWEETCHOC,
  COLOR_BAKERSCHOC,
  COLOR_FLESH,
  COLOR_NEWTAN,
  COLOR_NEWMIDNIGHTBLUE,
  COLOR_VERYDARKBROWN,
  COLOR_DARKBROWN,
  COLOR_DARKTAN,
  COLOR_GREENCOPPER,
  COLOR_DKGREENCOPPER,
  COLOR_DUSTYROSE,
  COLOR_HUNTERSGREEN,
  COLOR_SCARLET,
  COLOR_MED_PURPLE,
  COLOR_LIGHT_PURPLE,
  COLOR_VERY_LIGHT_PURPLE,
  COLOR_BLACK
};

const uint32_t ALL_COLORS_LENGTH = array_length(ALL_COLORS);

const uint32_t FLASH_COLORS_SEQUENCE[] = {
  COLOR_RED,
  COLOR_GREEN,
  COLOR_BLUE,
  COLOR_YELLOW,
  COLOR_VIOLET,
  COLOR_SCARLET
};

const uint32_t FLASH_COLORS_SEQUENCE_LENGTH = array_length(FLASH_COLORS_SEQUENCE);

#endif /* RGB_COLORS_H_ */